sudo: required

services:
  - docker

before_install:
  - docker build -t iffyx/DevOps/mydockerfrontend -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script:
  - docker run -e CI=true iffyx/DevOps/mydockerfrontend yarn test