sudo: required

services:
  - docker

before_install:
  - docker build -t iwonajx/my-frontend -f mydockerfrontend/Dockerfile.dev mydockerfrontend/.

script:
  - docker run -e CI=true iwonajx/my-frontend yarn test